# Generated by Django 2.0 on 2018-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
